
export const recipes = [
    {
      id: 1,
      title: 'Spaghetti Bolognese',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkiW51yZh6Wq5yNdGpbuniksIJ500nfMs-WQ&s',
      ingredients: ['pasta', 'ground beef', 'tomato sauce'],
      cuisine: 'Italian',
    },
    {
      id: 2,
      title: 'Chicken Curry',
      image: 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Instant-Pot-Chicken-Curry-Recipe.jpg',
      ingredients: ['chicken', 'curry powder', 'coconut milk'],
      cuisine: 'Indian',
    },
    {
      id: 3,
      title: 'Beef Tacos',
      image: 'https://brandsitesplatform-res.cloudinary.com/image/fetch/w_1540,c_scale,q_auto:eco,f_auto,fl_lossy,dpr_1.0,e_sharpen:85/https://assets.brandplatform.generalmills.com%2F-%2Fmedia%2Fproject%2Fgmi%2Foldelpaso%2Foldelpaso-us%2Frecipes%2Fqtcu578og0gukdk_kb_rmg_gmi_hi_res_jpeg.jpeg%3F%201540w',
      ingredients: ['ground beef', 'taco shells', 'cheese'],
      cuisine: 'Mexican',
    },
    {
      id: 4,
      title: 'Sushi Rolls',
      image: 'https://foreignfork.com/wp-content/uploads/2023/05/DragonRoll-FEATURE.jpg',
      ingredients: ['rice', 'nori', 'fish'],
      cuisine: 'Japanese',
    },
    {
      id: 5,
      title: 'Pad Thai',
      image: 'https://tenina.com/uploads/recipe-images/Pad-Thai-and-Sauce_Fotor.jpg',
      ingredients: ['noodles', 'peanuts', 'shrimp'],
      cuisine: 'Thai',
    },
    {
      id: 6,
      title: 'Caesar Salad',
      image: 'https://www.noracooks.com/wp-content/uploads/2022/06/vegan-caesar-salad-4.jpg',
      ingredients: ['lettuce', 'croutons', 'parmesan'],
      cuisine: 'American',
    },
    {
      id: 7,
      title: 'Butter Chicken',
      image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2023/04/butter-chicken-recipe.jpg',
      ingredients: ['chicken', 'butter', 'tomato sauce'],
      cuisine: 'Indian',
    },
    {
      id: 8,
      title: 'Pho',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr77o0Ceyn65zP0zXhwT-j2OdBnRl7rCpwWQ&s',
      ingredients: ['noodles', 'beef', 'broth'],
      cuisine: 'Vietnamese',
    },
    {
      id: 9,
      title: 'Pizza Margherita',
      image: 'https://eu.ooni.com/cdn/shop/articles/20220211142754-margherita-9920.jpg?crop=center&height=800&v=1644590277&width=800',
      ingredients: ['dough', 'mozzarella', 'tomatoes'],
      cuisine: 'Italian',
    },
    {
      id: 10,
      title: 'Falafel Wrap',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-Vs_oOG6nvvYFG5MZTaowq8foX5Sanejefw&s',
      ingredients: ['chickpeas', 'pita bread', 'tahini'],
      cuisine: 'Middle Eastern',
    },
    {
      id: 11,
      title: 'Fried Rice',
      image: 'https://recipe30.com/wp-content/uploads/2020/05/chicken-fried-rice.jpg',
      ingredients: ['rice', 'soy sauce', 'vegetables'],
      cuisine: 'Chinese',
    },
    {
      id: 12,
      title: 'Lasagna',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCCyIYfrfP-O1vyn18ehdt_OsLroUxvxOyw&s',
      ingredients: ['pasta', 'ground beef', 'cheese'],
      cuisine: 'Italian',
    },
    {
      id: 13,
      title: 'Beef Stroganoff',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNUtbRPDyXcOXdGrzqegGnzv4N4kY57eUNCQ&s',
      ingredients: ['beef', 'mushrooms', 'cream'],
      cuisine: 'Russian',
    },
    {
      id: 14,
      title: 'Paella',
      image: 'https://cdn.greatlifepublishing.net/wp-content/uploads/sites/2/2023/09/01082357/Paella-Mixta-Horizontal-4.jpg',
      ingredients: ['rice', 'seafood', 'saffron'],
      cuisine: 'Spanish',
    },
    {
      id: 15,
      title: 'Shakshuka',
      image: 'https://www.licious.in/blog/wp-content/uploads/2020/12/Shakshuka-min.jpg',
      ingredients: ['eggs', 'tomatoes', 'peppers'],
      cuisine: 'Middle Eastern',
    },
    {
      id: 16,
      title: 'Bibimbap',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4rkrmq_6FZ4iGF26sH3COHKMJaHweZnTtSQ&s',
      ingredients: ['rice', 'vegetables', 'egg'],
      cuisine: 'Korean',
    },
    {
      id: 17,
      title: 'Hamburger',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTENYnRh013tE7LrJCY-j0pTDFoJzJZtAx8qw&s',
      ingredients: ['beef patty', 'bun', 'lettuce'],
      cuisine: 'American',
    },
    {
      id: 18,
      title: 'Peking Duck',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHNiDv4aU6t5EPme6sE-TOSLy9swfGwdXShw&s',
      ingredients: ['duck', 'hoisin sauce', 'pancakes'],
      cuisine: 'Chinese',
    },
    {
      id: 19,
      title: 'Ratatouille',
      image: 'https://www.allrecipes.com/thmb/F1rucOY3FQT5Ic0oyxdLoqU_yKc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/222006-disneys-ratatouille-DDMFS-4x3-36eb15843ab548a79e7aab761dac92e1.jpg',
      ingredients: ['zucchini', 'eggplant', 'tomatoes'],
      cuisine: 'French',
    },
    {
      id: 20,
      title: 'Tiramisu',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyyYOkdhPnpnYvLOKiyYu1d0tK4kExFqYedg&s',
      ingredients: ['mascarpone', 'coffee', 'ladyfingers'],
      cuisine: 'Italian',
    },
    {
      id: 21,
      title: 'Moussaka',
      image: 'https://www.simplyrecipes.com/thmb/1T1BKHTpiSTSwNPdW2fXBMbcRZA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Vegetarian-Moussaka-LEAD-09-b005ce5289804189af024541410c4785.jpg',
      ingredients: ['eggplant', 'ground beef', 'béchamel sauce'],
      cuisine: 'Greek',
    },
    {
      id: 22,
      title: 'Chicken Parmesan',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrz1FSU_mi5ffLx2_HR0VzU5i87iyl915clw&s',
      ingredients: ['chicken', 'mozzarella', 'tomato sauce'],
      cuisine: 'Italian-American',
    },
    {
      id: 23,
      title: 'Goulash',
      image: 'https://zardyplants.com/wp-content/uploads/2020/09/Vegan-Goulash-01.jpg',
      ingredients: ['beef', 'paprika', 'potatoes'],
      cuisine: 'Hungarian',
    },
    {
      id: 24,
      title: 'Fish and Chips',
      image: 'https://forkandtwist.com/wp-content/uploads/2021/04/IMG_0102-500x500.jpg',
      ingredients: ['fish', 'potatoes', 'batter'],
      cuisine: 'British',
    },
    {
      id: 25,
      title: 'Gazpacho',
      image: 'https://www.allrecipes.com/thmb/d_1S6Av48F5LBfP-Z4W8VTD9U4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/222331-Chef-Johns-Gazpacho-ddmfs-4x3-2781-67624a59fa4c4375b9149d06f6c32348.jpg',
      ingredients: ['tomatoes', 'cucumber', 'bell peppers'],
      cuisine: 'Spanish',
    },
    {
      id: 26,
      title: 'Tom Yum Soup',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJxWz9cTtWmg8q9cNuygLcZY4j4LIvcnY8qA&s',
      ingredients: ['shrimp', 'lemongrass', 'lime'],
      cuisine: 'Thai',
    },
    {
      id: 27,
      title: 'Clam Chowder',
      image: 'https://www.allrecipes.com/thmb/ElqwjwX_F7u9wPDB6dfHYxYmVCY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/13078-New-England-Clam-Chowder-DDMFS-3X4-0560-e9b8d6db885546538990735f2d4d2199.jpg',
      ingredients: ['clams', 'potatoes', 'cream'],
      cuisine: 'American',
    },
    {
      id: 28,
      title: 'Burrito',
      image: 'https://cdn.britannica.com/13/234013-050-73781543/rice-and-chorizo-burrito.jpg',
      ingredients: ['beans', 'rice', 'cheese'],
      cuisine: 'Mexican',
    },
    {
      id: 29,
      title: 'Quiche Lorraine',
      image: 'https://media.houseandgarden.co.uk/photos/6189479a8373470f8394e2e1/3:2/w_1920,h_1280,c_limit/mary-berry-vogue-2-25jun13-pr_bt.jpg',
      ingredients: ['eggs', 'bacon', 'cream'],
      cuisine: 'French',
    },
    {
      id: 30,
      title: 'Eggs Benedict',
      image: 'https://static01.nyt.com/images/2021/04/30/dining/ar-eggs-benedict/ar-eggs-benedict-superJumbo.jpg',
      ingredients: ['eggs', 'ham', 'hollandaise sauce'],
      cuisine: 'American',
    },
  ];
  